name: Noodband genereren

on: 
  workflow_dispatch:

jobs:
  MicroMPX noodband:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Runner voorbereiden met FFmpeg
      run: sudo apt-get update -y && sudo apt-get install -y wget ffmpeg curl

    - name: StereoTool downloaden
      run: |
        wget https://www.stereotool.com/download/stereo_tool_cmd_64 -O /opt/stereotool
        sudo chmod +x /opt/stereotool

    - name: Oude noodband verwijderen
      run: rm -f /tmp/noodband.flac

    - name: Uur uit de audiologger downloaden
      run: |
        if [ ! -f "/tmp/noodband.mp3" ]; then
          wget https://audiologger.westeurope.cloudapp.azure.com/2024-02-28_05.mp3 -O /tmp/noodband.mp3
        else
          echo "File /tmp/noodband.mp3 already exists. Skipping download to save data on Azure."
        fi

    - name: MicroMPX noodband van 10min maken als test
      run: |
        ffmpeg -hide_banner -i /tmp/noodband.mp3 -t 600 -f wav -acodec pcm_s16le -ar 192000 -ac 2 - | /opt/stereotool -q -r 192000 - - -s $GITHUB_WORKSPACE/st_cleaned.ini | ffmpeg -hide_banner -i - -f wav -ac 1 -ar 192000 /tmp/noodband.flac

    - name: FLAC file uploaden
      run: curl --silent https://bashupload.com -T /tmp/noodband.flac
